### ISSUE TITLE
squareBracket does not look good on small resolutions

### ISSUE THREAD

**Issue by EricZhang456** [squarebracket-dev/squarebracket#61]
Valve plz fix
![Screenshot_20210801-144114](https://user-images.githubusercontent.com/32814750/127761888-ca70fee7-4911-40ef-9110-87e190dedf48.png)

**Comment by rollerozxa** [comment]
toggle desktop site

**Comment by rollerozxa** [comment]
toggle desktop site

![Screenshot_20210801-084615~2](https://user-images.githubusercontent.com/60856959/127762034-ef6a090c-71fc-4106-99fa-36c0e948079c.png)

**Comment by EricZhang456** [comment]
This isn't a fix damn

**Comment by chaziz94** [comment]
@rollerozxa this is because his screen's size is small

**Comment by rollerozxa** [comment]
his phone literally has a higher resolution than mine

**Comment by chaziz94** [comment]
well what's his DPI then

**Comment by EricZhang456** [comment]
It's a Pixel 4 (not XL), figure that out

**Comment by chaziz94** [comment]
does that happen on sbnext

**Comment by forkiesassds** [comment]
> 
> 
> does that happen on sbnext

It's even worse, since the UI framework wasn't built for mobile.

**Comment by chaziz94** [comment]
> 
> 
> > does that happen on sbnext
> 
> It's even worse, since the UI framework wasn't built for mobile.

there's no thing as a framework in the scss.

**Comment by PF94** [comment]
icty implemented mobile sbnext stuff during the time i was working on poktwo so this can be marked as fixed
